phy: qcom-qmp: Explicitly cast to type of qmp->cfq
Fixes a clang error (we can't make cfg const because it is modified in
three places):

../drivers/phy/phy-qcom-qmp.c:1456:11: error: assigning to 'struct
qmp_phy_cfg *' from 'const void *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>